### PR TITLE
[SDPA-2970] change display of dates in CMS to Australian style DD/MM/YYYY

### PR DESCRIPTION
**Pull request by vincent-gao**
### Jira
https://digital-engagement.atlassian.net/browse/SDPA-2970

### Changes
1. apply `d/m/Y - H:i` to the view.

### CODE REVIEW

**Review by GROwen — CHANGES_REQUESTED** [review]
@vincent-gao This change should happen new installs which means this should probably be added to `tide_core_install()` as well.

**Comment by vincent-gao** [comment]
> @vincent-gao This change should happen new installs which means this should probably be added to `tide_core_install()` as well.

Thanks @GROwen , yes. sure.it should be added to `tide_core_install()`

**Comment by vincent-gao** [comment]
> @vincent-gao This change should happen new installs which means this should probably be added to `tide_core_install()` as well.

Hey @GROwen , I think tide_core(https://github.com/dpc-sdp/tide_core/blob/develop/tide_core.install#L61) has done this for us. during the tide_core module installation, the install hook calls each of `tide_core_update_x` to run.

**Review by GROwen — APPROVED** [review]
>Hey @GROwen , I think tide_core(https://github.com/dpc-sdp/tide_core/blob/develop/tide_core.install#L61) has done this for us. during the tide_core module installation, the install hook calls each of tide_core_update_x to run.

Ah yes, we've got an open issue to refactor that logic out. It's not a good pattern to use. This can be cleaned up when that issue is actioned. Thanks @vincent-gao

**Pull request merged**
