### PR TITLE
[DDS-245] Fix wrong timezone is configured after a site install

### PR DESCRIPTION
**Pull request by mayurngondhkar**
Jira: https://digital-engagement.atlassian.net/browse/DDS-245

1. Add system.date.yml (copied from content VT)
image

### CODE REVIEW

**Review by MdNadimHossain — CHANGES_REQUESTED** [review]
@mayurngondhkar may be adding a behat test will be good as well

**Comment by anthony-malkoun** [comment]
> @mayurngondhkar may be adding a behat test will be good as well

Yes please. I would like all of these changes to have behat tests with them. To test we can run my draft branch of the reference site which will install a site from scratch.

**Comment by anthony-malkoun** [comment]
@mayurngondhkar / @MdNadimHossain I've been thinking about this. Should it actually live in `tide_core`? This is probably something that should be in `baywatch`, that is something that is for SDP only rather than all users of `tide`.

CC: @vincent-gao

**Comment by MdNadimHossain** [comment]
> @mayurngondhkar / @MdNadimHossain I've been thinking about this. Should it actually live in `tide_core`? This is probably something that should be in `baywatch`, that is something that is for SDP only rather than all users of `tide`.
> 
> CC: @vincent-gao

@anthony-malkoun hmm is that because the timezone defaulted to Melbourne only applies to the SDP clients and tide_core is open source and if other organization uses it, they might not want it to set to Melbourne time zone?

**Comment by vincent-gao** [comment]
> @mayurngondhkar / @MdNadimHossain I've been thinking about this. Should it actually live in `tide_core`? This is probably something that should be in `baywatch`, that is something that is for SDP only rather than all users of `tide`.
> 
> CC: @vincent-gao

Yes, agreed. non-SDP user  (NON Victoria user ⏲️ ) should able to change timezone settings.

**Comment by mayurngondhkar** [comment]
@anthony-malkoun True. As @MdNadimHossain mentioned being open source it should not be defaulted to a given timezone.

**Comment by anthony-malkoun** [comment]
I'm going to close this in favour of https://github.com/dpc-sdp/sdp-ansible-upgrade/pull/83 even though it's a WIP as it makes more sense for it to go there.

**Pull request closed without merging**
