### PR TITLE
[SDPA-2742] Altered scheduled_transitions module UI

### PR DESCRIPTION
**Pull request by vincent-gao**
https://digital-engagement.atlassian.net/browse/SDPA-2742

### CODE REVIEW

**Comment by vincent-gao** [comment]
we might want fully controllability of scheduled_transition Forms, rather than just alteration by using form_alter.

**Comment by GROwen** [comment]
@vincent-gao Where's the requirement for this work set out? I'm looking at the code but don't have any acceptance criteria to compare it against.

**Comment by vincent-gao** [comment]
> @vincent-gao Where's the requirement for this work set out? I'm looking at the code but don't have any acceptance criteria to compare it against.

Hi @GROwen , currently Jess wants the title of Tabs and Actions to be `Scheduled publishing`, and the date in forms to be Australian time format.

**Comment by vincent-gao** [comment]
> @vincent-gao Where's the requirement for this work set out? I'm looking at the code but don't have any acceptance criteria to compare it against.

yes. there is no AC currently. I will let Jess know.

**Comment by vincent-gao** [comment]
closed. we use https://github.com/dpc-sdp/tide_core/pull/87 instead.

**Pull request closed without merging**
