### PR TITLE
[SD-342] Removed delete option for approver role

### PR DESCRIPTION
**Pull request by yeniatencio**
### Jira
https://digital-vic.atlassian.net/browse/SD-343
### Problem/Motivation
Delete content option is available in the drop down and it should't .
### Fix
Implements HOOK_preprocess_views_view_field 
### Related PRs
BE testing link: https://nginx-php.pr-447.content-reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/
### Screenshots
Screenshot 2024-10-03 at 3 50 12 pm

### CODE REVIEW

**Review by vincent-gao — CHANGES_REQUESTED** [review]
hey @yeniatencio The change does not belong here. could you please take a look into `Drupal\tide_site_restriction\Plugin\views\field\TideNodeBulkForm`

**Comment by yeniatencio** [comment]
> hey @yeniatencio The change does not belong here. could you please take a look into `Drupal\tide_site_restriction\Plugin\views\field\TideNodeBulkForm`

Hey @vincent-gao , I was planning to move my code to tide_site_restriction.module. Is it what you are referring?

**Comment by vincent-gao** [comment]
> > hey @yeniatencio The change does not belong here. could you please take a look into `Drupal\tide_site_restriction\Plugin\views\field\TideNodeBulkForm`
> 
> Hey @vincent-gao , I was planning to move my code to tide_site_restriction.module. Is it what you are referring?

No, that's not what I meant. I think you should modify the `Drupal\tide_site_restriction\Plugin\views\field\TideNodeBulkForm`class to achieve what the ticket is requesting.

**Comment by yeniatencio** [comment]
> > > hey @yeniatencio The change does not belong here. could you please take a look into `Drupal\tide_site_restriction\Plugin\views\field\TideNodeBulkForm`
> > 
> > 
> > Hey @vincent-gao , I was planning to move my code to tide_site_restriction.module. Is it what you are referring?
> 
> No, that's not what I meant. I think you should modify the `Drupal\tide_site_restriction\Plugin\views\field\TideNodeBulkForm`class to achieve what the ticket is requesting.

Thanks @vincent-gao ! I have updated my code.

**Review by MdNadimHossain — APPROVED** [review]

**Review by vincent-gao — APPROVED** [review]

**Pull request merged**
