### PR TITLE
[SD-494] Enable linkset endpoint.

### PR DESCRIPTION
**Pull request by MdNadimHossain**
### Jira
https://digital-vic.atlassian.net/browse/SD-494
### Changed
Enabled linkset endpoint for all projects.

### CODE REVIEW

**Review by yeniatencio — APPROVED** [review]
LGTM.

**Review by vincent-gao — APPROVED** [review]
💯

**Review by anthony-malkoun — APPROVED** [review]
Is this a good place for our own feature flags?

**Comment by MdNadimHossain** [comment]
> Is this a good place for our own feature flags?

I think it is

**Pull request merged**
