### PR TITLE
[SDPA-2552] Add css hook alter for CKEditor to override styling for media library…

### PR DESCRIPTION
**Pull request by rubyllamadora**
### This adds css override to CKEditor styling to show media library label in the toolbar

Jira: https://digital-engagement.atlassian.net/browse/SDPA-2552
Related PR: https://github.com/dpc-sdp/tide_media/pull/46

Testing branch: https://nginx-php-content-vic-pr-947.lagoon.vicsdp.amazee.io/

### CODE REVIEW

**Comment by anthony-malkoun** [comment]
PR environment broken @rubyllamadora?

**Comment by rubyllamadora** [comment]
> PR environment broken @rubyllamadora?

Ugh looks like it sorry @anthony-malkoun . Something to do with search indexing. It worked on my local as I disabled the indexing. Will ping you later once PR env is working.

**Review by anthony-malkoun — APPROVED** [review]
Looks good to me. I'm assuming the `!important` was required?

**Review by vincent-gao — APPROVED** [review]

**Comment by rubyllamadora** [comment]
> Looks good to me. I'm assuming the `!important` was required?

Yep tried without it but the existing classes has higher specificity. Thanks for the review @anthony-malkoun  

> Looks good to me. I'm assuming the `!important` was required?

Yep, the existing `..cke_button_label` has higher specificity.

**Pull request merged**
