### PR TITLE
Fixed update hooks with incorrect use of $config_factory->getEditable().

### PR DESCRIPTION
**Pull request by sonnykt**
Fresh install is broken at may places due to incorrect use of `$config_factory->getEditable()` in update hooks.

On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>

### CODE REVIEW

**Comment by MdNadimHossain** [comment]
@sonnykt does the update_hooks run during a fresh install? My understanding was, only the install hook run during the fresh install and update hooks only runs for the existing project where the module is enabled :/

**Comment by sonnykt** [comment]
@MdNadimHossain we have this in `tide_core_install()` and it becomes troublesome:
```
$excluded = [
    'tide_core_update_8015',
    'tide_core_update_8038',
    'tide_core_update_8043',
  ];
  $functions = get_defined_functions();
  foreach ($functions['user'] as $function) {
    if (strpos($function, 'tide_core_update_') === 0) {
      // We don't want the tide_core_update_8015 to run during the CI.
      if (in_array($function, $excluded)) {
        continue;
      }
      call_user_func($function);
    }
  }```

**Comment by anthony-malkoun** [comment]
So, to be clear, normally an install _doesn't_ run update hooks but in the case of `tide_core` we're manually forcing a run of (most of) the update hooks. Sound right?

**Comment by vincent-gao** [comment]
> So, to be clear, normally an install _doesn't_ run update hooks but in the case of `tide_core` we're manually forcing a run of (most of) the update hooks. Sound right?

 Yes.

**Comment by sonnykt** [comment]
> So, to be clear, normally an install _doesn't_ run update hooks but in the case of `tide_core` we're manually forcing a run of (most of) the update hooks. Sound right?

yes, it's been there since inception due to the laziness of developers 😂

**Review by anthony-malkoun — APPROVED** [review]

**Pull request merged**
