### PR TITLE
Fixing a dependency issue

### PR DESCRIPTION
**Pull request by vincent-gao**
https://www.drupal.org/project/viewsreference/issues/3096956#comment-13370643
```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:
                                                                                                                                   
  The service "viewsreference.normalizer.views_reference_item.hal" has a dependency on a non-existent service "hal.link_manager". 
```

### CODE REVIEW

**Comment by vincent-gao** [comment]
also, we will skip the ClamAV test.

**Comment by GROwen** [comment]
> also, we will skip the ClamAV test.

Why is this necessary @vincent-gao ?

**Comment by vincent-gao** [comment]
> > also, we will skip the ClamAV test.
> 
> Why is this necessary @vincent-gao ?

@anthony-malkoun told me that there is no ClamAV in our lagoon or CI (we don't remember it was lagoon or CI ), so we skip this scenario . @GROwen

**Comment by vincent-gao** [comment]
> > also, we will skip the ClamAV test.
> 
> Why is this necessary @vincent-gao ?
@GROwen , I've deleted the skip tag. thanks

**Pull request merged**
