### PR TITLE
Fixes the issue where CKE 5 Interface not loading

### PR DESCRIPTION
**Pull request by vincent-gao**
### Problem/Motivation

https://www.drupal.org/project/entity_embed/issues/3272732 has been merged, but it introduces a new issue to Drupal 9, where CKEditor 5 Interface is not loading on text formats using entity embed.

### Fix
https://www.drupal.org/project/entity_embed/issues/3396133
https://git.drupalcode.org/project/entity_embed/-/merge_requests/26/diffs

### CODE REVIEW

**Review by anthony-malkoun — COMMENTED** [review]
Is the patch not on drupal.org as well? Why not use that one?

**Comment by vincent-gao** [comment]
> Is the patch not on drupal.org as well? Why not use that one?

hey @anthony-malkoun, There is no patch file available on Drupal.org, only a PR. https://git.drupalcode.org/project/entity_embed/-/merge_requests/26

**Comment by krakerag** [comment]
Having a static patch is better than the PR, which can change. Is our pattern to store a patch on drupal.org or locally? Whichever the chosen pattern is, lets match that.

**Comment by vincent-gao** [comment]
hey @krakerag 
The patch is static and stored locally,
 https://github.com/dpc-sdp/tide_core/pull/449/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R248

**Review by anthony-malkoun — APPROVED** [review]

**Pull request merged**
